version: "3.8"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      # Set DOMAIN_NAME in an .env file or override via environment
      - DOMAIN_NAME=
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web
  n8n:
    image: n8nio/n8n:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - web
  zep:
    image: ghcr.io/getzep/zep:latest
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - web
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:
  n8n-data:
  qdrant-data:

networks:
  web: